version: "3.8"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data:
